"""rev1

Revision ID: dd5da92a9c3d
Revises: f92ce9ac3429
Create Date: 2022-05-17 18:22:11.216973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd5da92a9c3d'
down_revision = 'f92ce9ac3429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('employee', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'is_superuser')
    op.drop_column('employee', 'is_active')
    # ### end Alembic commands ###
